resource-pack:
  url: "https://github.com/RuskLabo/CreateSMPdoc/releases/download/0.67/iem-resorcepack.zip"
  hash: "" # 任意（更新検知用）
  prompt: "サーバー専用リソースパックを適用してください。"
  force: true

hit-sounds:
  headshot: "custom_hit"
  penetration-success: "ENTITY_ZOMBIE_ATTACK_IRON_DOOR"
  penetration-failed: "ITEM_ARMOR_EQUIP_IRON"

ai_log:
  enabled: true
  sample_interval_ticks: 5
  capture_raycast: false
  max_raid_logs: 50
  async_write: true
